# Generated by Django 3.0.2 on 2020-07-01 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babu', '0002_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='username',
        ),
    ]
